"""empty message

Revision ID: 57864bd07e81
Revises: 93804590f473
Create Date: 2023-12-20 15:32:34.668188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57864bd07e81'
down_revision = '93804590f473'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('confirmed')

    # ### end Alembic commands ###
