"""empty message

Revision ID: 785b0245bcbb
Revises: e4b1dfc9bc45
Create Date: 2023-12-20 21:05:39.670018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '785b0245bcbb'
down_revision = 'e4b1dfc9bc45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_blogs_date'), ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blogs_date'))
        batch_op.drop_column('date')

    # ### end Alembic commands ###
