"""empty message

Revision ID: e4b1dfc9bc45
Revises: 57864bd07e81
Create Date: 2023-12-20 16:24:10.902996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4b1dfc9bc45'
down_revision = '57864bd07e81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('body', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_column('body')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
